---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "dataspace-connector.fullname" . }}
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
    {{ $key }}: "{{ $val }}"
  {{- end}}
  {{- if .Values.postgresql.enabled }}
    SPRING_DATASOURCE_PLATFORM: "postgres"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresqlDatabase }}"
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
    SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  {{- end}}
